comment:
  layout: reach
  behavior: new
  require_changes: true

coverage:
  range: 0..100
  round: nearest
  precision: 1
  status:
    patch:
      default:
        target: 50%
        threshold: 10%
    project:
      default:
        target: 50%
        threshold: 10%
      builders:
        flags: [builders]
      image:
        flags: [image]
      image-config:
        flags: [image-config]
      image-optimizer:
        flags: [image-optimizer]
      core-web-vitals-app:
        flags: [core-web-vitals-app]

flags:
  builders:
    paths:
      - coverage/libs/builders
  image:
    paths:
      - coverage/libs/image
  image-config:
    paths:
      - coverage/libs/image-config
  image-optimizer:
    paths:
      - coverage/libs/image-optimizer
  core-web-vitals-app:
    paths:
      - coverage/libs/core-web-vitals-app
