name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  npm:
    name: NPM
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: ${{ github.event.number }}
      NX_BASE: ${{ github.event_name == 'pull_request' && 'remotes/origin/main' || github.event.before }}
      NX_RUN_GROUP: ${{ github.run_id }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x

      - name: NPM
        uses: ng-easy/npm-setup@v1.7.2

  build:
    name: Build
    needs: [npm]
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: ${{ github.event.number }}
      NX_BASE: ${{ github.event_name == 'pull_request' && 'remotes/origin/main' || github.event.before }}
      NX_RUN_GROUP: ${{ github.run_id }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x

      - name: NPM
        uses: ng-easy/npm-setup@v1.7.2
        with:
          nx-key: build

      - name: Build
        run: |
          npm run build
          npm run favicons

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build-artifacts
          path: dist

  lint:
    name: Lint
    needs: [npm]
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: ${{ github.event.number }}
      NX_BASE: ${{ github.event_name == 'pull_request' && 'remotes/origin/main' || github.event.before }}
      NX_RUN_GROUP: ${{ github.run_id }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Fetch latest base branch
        run: git fetch origin main

      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x

      - name: NPM
        uses: ng-easy/npm-setup@v1.7.2
        with:
          nx-key: lint

      - name: Lint
        run: npm run ci:affected:lint

  test:
    name: Test
    needs: [npm]
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: ${{ github.event.number }}
      NX_BASE: ${{ github.event_name == 'pull_request' && 'remotes/origin/main' || github.event.before }}
      NX_RUN_GROUP: ${{ github.run_id }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Fetch latest base branch
        run: git fetch origin main

      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x

      - name: NPM
        uses: ng-easy/npm-setup@v1.7.2
        with:
          nx-key: test

      - name: Test
        run: npm run ci:affected:test

  e2e:
    name: e2e tests
    needs: [npm, build]
    runs-on: ubuntu-latest
    env:
      NX_BRANCH: ${{ github.event.number }}
      NX_BASE: ${{ github.event_name == 'pull_request' && 'remotes/origin/main' || github.event.before }}
      NX_RUN_GROUP: ${{ github.run_id }}
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Fetch latest base branch
        run: git fetch origin main

      - name: Setup Node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14.x

      - name: NPM
        uses: ng-easy/npm-setup@v1.7.2
        with:
          NX_KEY: e2e

      - name: Download build artifacts
        uses: actions/download-artifact@v2.0.10
        with:
          name: build-artifacts
          path: dist

      - name: e2e tests
        run: npm run ci:affected:e2e

      - name: e2e test upload diffs
        uses: actions/upload-artifact@v2.2.4
        if: failure()
        with:
          name: visual-testing-diffs
          path: dist/cypress/apps/core-web-vitals-app-e2e/snapshot-diffs
          if-no-files-found: ignore

  lighthouse:
    name: Lighthouse audit
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }} # https://github.com/GoogleChrome/lighthouse-ci/issues/172
          fetch-depth: 20 # https://github.com/GoogleChrome/lighthouse-ci/blob/main/docs/troubleshooting.md

      - name: Download build artifacts
        uses: actions/download-artifact@v2.0.10
        with:
          name: build-artifacts
          path: dist

      - name: Lighthouse audit
        uses: treosh/lighthouse-ci-action@7.0.0
        with:
          configPath: ./lighthouserc.json
          runs: 3
          uploadArtifacts: true
          temporaryPublicStorage: true
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
