name: Release
on:
  workflow_dispatch: # manual release
  schedule:
    - cron: '0 5 * * *' # scheduled nightly release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.0.2
        with:
          fetch-depth: 0
          persist-credentials: false # Needed so that semantic release can use the admin token

      - name: Fetch latest base branch
        run: git fetch origin main

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 16.x

      - name: NPM
        uses: ng-easy/npm-setup@v2.0.12
        with:
          nx-key: build

      - name: Build release scripts
        uses: mansagroup/nrwl-nx-action@v2.1.0
        with:
          targets: build
          projects: builders
          nxCloud: 'true'

      - name: Release
        uses: mansagroup/nrwl-nx-action@v2.1.0
        with:
          targets: release
          nxCloud: 'true'
          affected: 'false'
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Personal access token with repo permissions

      - uses: nashmaniac/create-issue-action@v1.1
        if: failure()
        name: Create Issue
        with:
          title: 'bug(release): pipeline failed'
          token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
          labels: bug
          body: GitHub [release workflow](https://github.com/ng-easy/platform/actions/workflows/release.yml) failed
